apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31080
    name: http
  - port: 443
    nodePort: 31443
    name: https
  selector:
    app: nginx
