apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: NodePort
  ports:    
  - name: traefik-http
    port: 80
    nodePort: 30080
  - name: traefik-https
    port: 443
    nodePort: 30443
  selector:
    app: traefik