apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  type: NodePort
  ports:
  - name: admin-interface
    port: 8083
    # targetPort: 80
    protocol: TCP
  - name: http-api
    port: 8086
    # targetPort: 80
    protocol: TCP
  selector:
    app: influxdb

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb-graphite
spec:
  type: NodePort
  ports:
  - name: graphite
    port: 2003
    nodePort: 32003
    # targetPort: 80
    protocol: TCP
  selector:
    app: influxdb

